services:
  - type: web
    name: laravel-mini-cart
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install
      php artisan config:clear
      php artisan optimize
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
